/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VECTOR_H_RPCGEN
#define _VECTOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include <sys/time.h>

struct pass {
	int data[4];
};
typedef struct pass pass;

struct answer {
	int data[2];
};
typedef struct answer answer;

#define VECTORPROG 0x20000064
#define VECTORVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  answer * add_1(pass *, CLIENT *);
extern  answer * add_1_svc(pass *, struct svc_req *);
extern int vectorprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  answer * add_1();
extern  answer * add_1_svc();
extern int vectorprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pass (XDR *, pass*);
extern  bool_t xdr_answer (XDR *, answer*);

#else /* K&R C */
extern bool_t xdr_pass ();
extern bool_t xdr_answer ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VECTOR_H_RPCGEN */
